[project]
name = "python-scripts-using-gowaylee-cc-hooks"
version = "0.1.0"
description = "Claude Code hooks that are Python scripts using https://github.com/GowayLee/cchooks"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cchooks>=0.1.4",
    "desktop-notifier>=3.5.6",
]
